#version 450

#extension GL_EXT_shader_16bit_storage : require
#extension GL_AMD_gpu_shader_half_float: enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable
#extension GL_EXT_shader_buffer_int64 : enable

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

#include "common.comp"

layout(set = 0, binding = 0) buffer LhsBuffer {
    OUTER_TYPE lhs_data[];
};
layout(set = 0, binding = 1) buffer RhsBuffer {
    OUTER_TYPE rhs_data[];
};
layout(set = 0, binding = 2) buffer OutputBuffer {
    OUTER_TYPE output_data[];
};
layout(push_constant) uniform PushConstants {
    uint a_rank;
    uint a_base;
    uint a_shape[MAX_RANK];
    uint a_stride[MAX_RANK];
    uint b_rank;
    uint b_base;
    uint b_shape[MAX_RANK];
    uint b_stride[MAX_RANK];
} pc;

#if BF16
    #define CAST_OUT(x) uint16_t((floatBitsToUint(x) + 0x8000u) >> 16u)
    #define CAST_IN(x) uintBitsToFloat(uint(x) << 16u)
#else
    #define CAST_OUT(x) OUTER_TYPE(x)
    #define CAST_IN(x) INNER_TYPE(x)
#endif

void add_op(uint idx, uint a_idx, uint b_idx) {
    output_data[idx] = CAST_OUT(CAST_IN(lhs_data[a_idx]) + CAST_IN(rhs_data[b_idx]));
}

void sub_op(uint idx, uint a_idx, uint b_idx) {
    output_data[idx] = CAST_OUT(CAST_IN(lhs_data[a_idx]) - CAST_IN(rhs_data[b_idx]));
}

void div_op(uint idx, uint a_idx, uint b_idx) {
    output_data[idx] = CAST_OUT(CAST_IN(lhs_data[a_idx]) / CAST_IN(rhs_data[b_idx]));
}

void mul_op(uint idx, uint a_idx, uint b_idx) {
    output_data[idx] = CAST_OUT(CAST_IN(lhs_data[a_idx]) * CAST_IN(rhs_data[b_idx]));
}

void minimum_op(uint idx, uint a_idx, uint b_idx) {
    output_data[idx] = CAST_OUT(min(CAST_IN(lhs_data[a_idx]), CAST_IN(rhs_data[b_idx])));
}

void maximum_op(uint idx, uint a_idx, uint b_idx) {
    output_data[idx] = CAST_OUT(max(CAST_IN(lhs_data[a_idx]), CAST_IN(rhs_data[b_idx])));
}

void main() {
    uint idx = global_linear_id();
    uint total_elems = 1;
    for (uint i = 0; i < pc.a_rank; ++i) {
        // Handle dim size 0 safely - if any dim is 0, total elems is 0
        if (pc.a_shape[i] == 0) {
            total_elems = 0;
            break;
        }
        total_elems *= pc.a_shape[i];
    }
    if (idx >= total_elems) { return; }
    uint a_idx = get_physical_index(pc.a_rank, pc.a_base, pc.a_shape, pc.a_stride, idx);
    uint b_idx = get_physical_index(pc.b_rank, pc.b_base, pc.b_shape, pc.b_stride, idx);
    OP(idx, a_idx, b_idx);
}
