#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_AMD_gpu_shader_half_float: enable

layout(local_size_x = 256) in;

#include "common.comp"

#if SRC_BF16
    #define CAST(x) uintBitsToFloat(uint(x) << 16u)
#endif
#if DST_BF16
    #define CAST(x) uint16_t((floatBitsToUint(x) + 0x8000u) >> 16u)
#endif
#if NEED_UINT_CAST
    #define CAST(x) uint(x)
#endif
#ifndef CAST
    #define CAST(x) (x)
#endif

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0) buffer Input {
    SRC_TYPE input_data[];
};
layout(set = 0, binding = 1) buffer Output {
    DST_TYPE output_data[];
};
layout(push_constant) uniform PushConstants {
    uint rank;
    uint base;
    uint shape[MAX_RANK];
    uint stride[MAX_RANK];
} pc;

void main() {
    uint idx = global_linear_id();
    uint total_elems = 1;
    for (uint i = 0; i < pc.rank; ++i) {
        // Handle dim size 0 safely - if any dim is 0, total elems is 0
        if (pc.shape[i] == 0) {
            total_elems = 0;
            break;
        }
        total_elems *= pc.shape[i];
    }
    if (idx >= total_elems) return;
    uint a_idx = get_physical_index(pc.rank, pc.base, pc.shape, pc.stride, idx);
    output_data[idx] = DST_TYPE(CAST(input_data[a_idx]));
}
