#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_AMD_gpu_shader_half_float: enable

layout(local_size_x = 256) in;

#include "common.comp"

#if SRC_BF16
    #define CAST(x) uintBitsToFloat(uint(x) << 16u)
#endif
#if DST_BF16
    #define CAST(x) uint16_t((floatBitsToUint(x) + 0x8000u) >> 16u)
#endif
#if NEED_UINT_CAST
    #define CAST(x) uint(x)
#endif
#ifndef CAST
    #define CAST(x) (x)
#endif

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
layout(set = 0, binding = 0) buffer Input {
    SRC_TYPE input_data[];
};
layout(set = 0, binding = 1) buffer Output {
    DST_TYPE output_data[];
};
layout(push_constant) uniform PushConstants {
    uint base;
    uint rank;         // number of dimensions
    uvec4 shape;       // padded shape (unused dimensions set to 1)
    uvec4 stride;      // padded stride (unused dimensions set to 1)
} pc;

// This function converts a linear index to a physical index using the full
// multi-dimensional layout. We assume row-major ordering.
uint get_strided_index(uint lin_idx) {
    uint remaining = lin_idx;
    uint phys_idx = 0;
    if (pc.rank > 0u) {
        uint prod = 1u;
        if (pc.rank > 1u) { prod = pc.shape.y * pc.shape.z * pc.shape.w; }
        uint i0 = remaining / prod;
        remaining = remaining % prod;
        phys_idx += i0 * pc.stride.x;
    }
    if (pc.rank > 1u) {
        uint prod = 1u;
        if (pc.rank > 2u) { prod = pc.shape.z * pc.shape.w; }
        uint i1 = remaining / prod;
        remaining = remaining % prod;
        phys_idx += i1 * pc.stride.y;
    }
    if (pc.rank > 2u) {
        uint prod = 1u;
        if (pc.rank > 3u) { prod = pc.shape.w; }
        uint i2 = remaining / prod;
        remaining = remaining % prod;
        phys_idx += i2 * pc.stride.z;
    }
    if (pc.rank > 3u) {
        uint i3 = remaining;
        phys_idx += i3 * pc.stride.w;
    }
    return pc.base + phys_idx;
}

void main() {
    uint total_elements = pc.shape.x * pc.shape.y * pc.shape.z * pc.shape.w;
    uint idx = get_strided_index(global_linear_id());
    if (idx >= total_elements) return;
    output_data[idx] = DST_TYPE(CAST(input_data[idx]));
}
