#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_AMD_gpu_shader_half_float : enable
#extension GL_EXT_shader_atomic_float : enable
//#extension GL_EXT_shader_atomic_int64 : enable

layout(local_size_x = 256) in;

layout(set = 0, binding = 0) buffer Input {
    TYPE input_data[];
};
layout(set = 0, binding = 1) buffer Indices {
    IDX_TYPE index_data[];
};
layout(set = 0, binding = 2) buffer Output {
    TYPE output_data[];
};

layout(push_constant) uniform PushConstants {
    uint total_src_elems;   // driven by src
    uint rank;              // rank of tensors
    uint selected_dim;      // dim along which to scatter
    uvec4 input_strides;    // src strides
    uvec4 output_strides;   // dst strides
};

void main() {
    uint linear_idx = gl_GlobalInvocationID.x;
    if (linear_idx >= total_src_elems) return;

    // Decode src coordinate
    uvec4 coord = uvec4(0);
    uint rem = linear_idx;
    for (uint d = 0; d < rank; ++d) {
        coord[d] = rem / input_strides[d];
        rem %= input_strides[d];
    }

    // Read index and rewrite dst coordinate
    uint j = coord[selected_dim];
    coord[selected_dim] = uint(index_data[j]);

    // Compute dst linear index
    uint dst_idx = 0;
    for (uint d = 0; d < rank; ++d) {
        dst_idx += coord[d] * output_strides[d];
    }

    atomicAdd(output_data[dst_idx], input_data[linear_idx]);
}
