#version 450

#extension GL_EXT_shader_16bit_storage : require
#extension GL_AMD_gpu_shader_half_float: enable

#if BF16
    #define CAST_OUT(x) uint16_t((floatBitsToUint(x) + 0x8000u) >> 16u)
    #define CAST_IN(x) uintBitsToFloat(uint(x) << 16u)
#else
    #define CAST_OUT(x) OUTER_TYPE(x)
    #define CAST_IN(x) INNER_TYPE(x)
#endif

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

// Buffer bindings
layout(set = 0, binding = 0) buffer InputBuffer {
    OUTER_TYPE input_data[];
};
layout(set = 0, binding = 1) buffer OutputBuffer {
    OUTER_TYPE output_data[];
};
layout(push_constant) uniform PushConstants {
    uint base;
    uint rank;         // number of dimensions
    uvec4 shape;       // padded shape (unused dimensions set to 1)
    uvec4 stride;      // padded stride (unused dimensions set to 1)
} pc;

const INNER_TYPE HALF = INNER_TYPE(0.5);
const INNER_TYPE ONE = INNER_TYPE(1.0);

// This function converts a linear index to a physical index using the full
// multi-dimensional layout. We assume row-major ordering.
uint get_strided_index(uint lin_idx) {
    uint remaining = lin_idx;
    uint phys_idx = 0;
    if (pc.rank > 0u) {
        uint prod = 1u;
        if (pc.rank > 1u) { prod = pc.shape.y * pc.shape.z * pc.shape.w; }
        uint i0 = remaining / prod;
        remaining = remaining % prod;
        phys_idx += i0 * pc.stride.x;
    }
    if (pc.rank > 1u) {
        uint prod = 1u;
        if (pc.rank > 2u) { prod = pc.shape.z * pc.shape.w; }
        uint i1 = remaining / prod;
        remaining = remaining % prod;
        phys_idx += i1 * pc.stride.y;
    }
    if (pc.rank > 2u) {
        uint prod = 1u;
        if (pc.rank > 3u) { prod = pc.shape.w; }
        uint i2 = remaining / prod;
        remaining = remaining % prod;
        phys_idx += i2 * pc.stride.z;
    }
    if (pc.rank > 3u) {
        uint i3 = remaining;
        phys_idx += i3 * pc.stride.w;
    }
    return pc.base + phys_idx;
}

void neg_op(uint idx, uint a_idx) {
    output_data[idx] = CAST_OUT(-CAST_IN(input_data[a_idx]));
}

void abs_op(uint idx, uint a_idx) {
    output_data[idx] = CAST_OUT(abs(CAST_IN(input_data[a_idx])));
}

void sign_op(uint idx, uint a_idx) {
    output_data[idx] = CAST_OUT(sign(CAST_IN(input_data[a_idx])));
}

void gelu_op(uint idx, uint a_idx) {
    const INNER_TYPE COEF_A = INNER_TYPE(0.79788456) + INNER_TYPE(0.000000000802865355);
    const INNER_TYPE COEF_B = INNER_TYPE(0.04471509) + INNER_TYPE(-0.0000000026068047);
    INNER_TYPE x = CAST_IN(input_data[a_idx]);
    INNER_TYPE x_cubed = x * x * x;
    INNER_TYPE inner = COEF_A * (x + COEF_B * x_cubed);
    INNER_TYPE cdf = HALF * (ONE + tanh(inner));
    output_data[idx] = CAST_OUT(x * cdf);
}

// Custom erf approximation
INNER_TYPE erf_approx(INNER_TYPE x) {
    const INNER_TYPE a1 = INNER_TYPE(0.25482959) + INNER_TYPE(0.000000002091);
    const INNER_TYPE a2 = INNER_TYPE(-0.28449674) + INNER_TYPE(0.000000003751);
    const INNER_TYPE a3 = INNER_TYPE(1.42141378) + INNER_TYPE(-0.000000038331);
    const INNER_TYPE a4 = INNER_TYPE(-1.45315206) + INNER_TYPE(0.00000003259);
    const INNER_TYPE a5 = INNER_TYPE(1.06140542) + INNER_TYPE(0.000000009758);
    const INNER_TYPE p  = INNER_TYPE(0.3275911) + INNER_TYPE(0.000000000330);
    INNER_TYPE s = sign(x);
    x = abs(x);
    INNER_TYPE t = ONE / (ONE + p * x);
    INNER_TYPE y = ONE - (((((a5 * t + a4) * t) + a3) * t + a2) * t + a1) * t * exp(-x * x);
    return s * y;
}

void gelu_erf_op(uint idx, uint a_idx) {
    INNER_TYPE x = CAST_IN(input_data[a_idx]);
    INNER_TYPE cdf = HALF * (ONE + erf_approx(x / sqrt(2.0)));
    output_data[idx] = CAST_OUT(x * cdf);
}

void erf_op(uint idx, uint a_idx) {
    INNER_TYPE x = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(erf_approx(x));
}

void silu_op(uint idx, uint a_idx) {
    INNER_TYPE x = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(x / (ONE + exp(-x)));
}

void ceil_op(uint idx, uint a_idx) {
    output_data[idx] = CAST_OUT(ceil(CAST_IN(input_data[a_idx])));
}

void floor_op(uint idx, uint a_idx) {
    output_data[idx] = CAST_OUT(floor(CAST_IN(input_data[a_idx])));
}

float c_round(float x) {
    return (x >= 0.0) ? floor(x + 0.5) : ceil(x - 0.5);
}

void round_op(uint idx, uint a_idx) {
    output_data[idx] = CAST_OUT(c_round(CAST_IN(input_data[a_idx])));
}

void sqr_op(uint idx, uint a_idx) {
    INNER_TYPE data = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(data * data);
}

void sqrt_op(uint idx, uint a_idx) {
    INNER_TYPE data = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(sqrt(data));
}

void sin_op(uint idx, uint a_idx) {
    INNER_TYPE data = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(sin(data));
}

void cos_op(uint idx, uint a_idx) {
    INNER_TYPE data = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(cos(data));
}

void tan_op(uint idx, uint a_idx) {
    INNER_TYPE data = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(tan(data));
}

void sigmoid_op(uint idx, uint a_idx) {
    INNER_TYPE data = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(1.0 / (1.0 + exp(-data)));
}

void exp_op(uint idx, uint a_idx) {
    INNER_TYPE data = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(exp(data));
}

void log_op(uint idx, uint a_idx) {
    INNER_TYPE data = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(log(data));
}

void recip_op(uint idx, uint a_idx) {
    INNER_TYPE data = CAST_IN(input_data[a_idx]);
    output_data[idx] = CAST_OUT(1.0 / data);
}

void main() {
    uint total_elems = pc.shape.x * pc.shape.y * pc.shape.z * pc.shape.w;
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= total_elems) { return; }
    uint a_idx = get_strided_index(idx);
    OP(idx, a_idx);
}
